POST http://localhost:8080/api/Ingredient
Content-Type: application/json

{
  "ingredient" : 1
}

###

POST http://localhost:8080/api/Ingredient
Content-Type: application/json

{
  "ingredient" : 2
}

###

POST http://localhost:8080/api/Ingredient
Content-Type: application/json

{
  "ingredient" : 3
}

###

POST http://localhost:8080/api/recipe
Content-Type: application/json

{
  "name": "김",
  "ingredients": [
    { "ingredient": 1 }
  ],
  "steps": [
  ]
}

###

POST http://localhost:8080/api/recipe
Content-Type: application/json

{
  "name": "밤",
  "ingredients": [
    { "ingredient": 2 }
  ],
  "steps": [
  ]
}

###

POST http://localhost:8080/api/recipe
Content-Type: application/json

{
  "name": "김밥",
  "ingredients": [
    { "ingredient": 1 },
    { "ingredient": 2 }
  ],
  "steps": [
  ]
}

###

POST http://localhost:8080/api/recipe
Content-Type: application/json

{
  "name": "김밥2",
  "ingredients": [
    { "ingredient": 1 },
    { "ingredient": 2 }
  ],
  "steps": [
  ]
}

###

POST http://localhost:8080/api/recipe
Content-Type: application/json

{
  "name": "김밥김밥",
  "ingredients": [
    { "ingredient": 1 },
    { "ingredient": 2 },
    { "ingredient": 3 }
  ],
  "steps": [
  ]
}

###

GET http://localhost:8080/api/recipe/search
Content-Type: application/json

{
  "recipeIngredientDtos" : [
    { "ingredient":  1 }
  ]
}