POST http://localhost:8080/api/Ingredient
Content-Type: application/json

{
  "ingredient" : 0
}

###

POST http://localhost:8080/api/Ingredient
Content-Type: application/json

{
  "ingredient" : 1
}

###

POST http://localhost:8080/api/recipe
Content-Type: application/json

{
  "name": "김밥",
  "description": "꿀",
  "ingredients": [
    { "ingredient": 0 },
    { "ingredient": 1 }
  ],
  "steps": [
    {
      "description": "1. 김 깔고",
      "imagePath": "../static/1.png"
    },
    {
      "description": "2. 밥 깔고",
      "imagePath": "../static/2.png"
    }
  ]
}

###

GET http://localhost:8080/api/recipe/1

###

GET http://localhost:8080/api/recipe/read/6

###

PUT http://localhost:8080/api/recipe/1/ingredient/0

###

PUT http://localhost:8080/api/recipe/1/like

###

PUT http://localhost:8080/api/recipe/1/like

###

POST http://localhost:8080/api/recipe/1/comment
Content-Type: application/json

{
  "author" : "me",
  "content" : "look good!",
  "password" : "1234"
}

###

GET http://localhost:8080/api/recipe/1

